[phases.setup]
nixPkgs = ['python39', 'nodejs-18_x', 'postgresql_16']

[phases.install]
cmds = [
    'cd melbourne-parking-website/backend && pip install -r requirements.txt',
    'cd melbourne-parking-website/frontend && npm install'
]

[phases.build]
cmds = [
    'cd melbourne-parking-website/frontend && npm run build'
]

[start]
cmd = 'cd melbourne-parking-website/backend && python run.py'
