[phases.setup]
aptPkgs = ['python3', 'python3-pip', 'nodejs', 'npm']

[phases.install]
cmds = [
    'cd melbourne-parking-website/backend && pip3 install -r requirements.txt',
    'cd melbourne-parking-website/frontend && npm install'
]

[phases.build]
cmds = [
    'cd melbourne-parking-website/frontend && npm run build'
]

[start]
cmd = 'cd melbourne-parking-website/backend && python3 run.py'
