[phases.setup]
nixPkgs = ['python39', 'nodejs-18_x', 'postgresql_16']

[phases.install]
cmds = [
    'cd backend && pip install -r requirements.txt',
    'cd frontend && npm install'
]

[phases.build]
cmds = [
    'cd frontend && npm run build'
]

[start]
cmd = 'cd backend && python run.py'
