[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python run.py"
healthcheckPath = "/api/parking/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = "8000"
FLASK_ENV = "production"
PYTHONPATH = "/app/backend"
